---
- name: Setup Xprofile Bastion
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup variable
      include_vars: vars/vpc_setup

    - name: Import VPC setup variable
      include_vars: vars/output_vars

    - name: Create xprofile ec2 key
      ec2_key:
        name: xprofile-key
        region: "{{region}}"
      register: key_out

    - name: Save private key into file
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 8600
      when: key_out.changed

    - name: Create a security group
      ec2_group:
          name: Bastion-host-sg
          description: security group for bastion host
          region: "{{region}}"
          vpc_id: "{{vpcid}}"
          rules:
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: "{{MYIP}}"
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: "{{MYIP}}"
      register: bastion_sg_out

    - name: creation bastion host
      ec2_instance:
        name: "bastion_host"
        key_name: xprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image_id: "{{bastion_ami}}"
        network:
          assign_public_ip: yes
        wait: yes
        wait_timeout: 300
        tags:
           Name: "bastion_host"
        #count: 1
        security_groups: ["{{bastion_sg_out.group_id}}"]
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastion_host_out
    
    - debug:
        var: bastion_host_out

    - name: Insert/Update 'Bastion Security Group' in vars/output_vars
      blockinfile:
        path: vars/output_vars
        backup: yes
        block: |
          bastion_sg_id: {{bastion_sg_out.group_id}}