---
- name: Setup Xprofile Bastion
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup variable
      include_vars: vars/bastion_setup

    - name: Import VPC setup variable
      include_vars: vars/output_vars

    - name: Create xprofile ec2 key
      ec2_key:
        name: xprofile-key
        region: "{{region}}"
      register: key_out

    - name: Save private key into file
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 8600
      when: key_out.changed

    - name: Create Sec grp for bastion
      ec2_group:
        name: Bastion-host-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules: 
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_id: "{{MYIP}}"
      register: bastion_out

    - name: creation bastion host
      ec2:
        key_name: xprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
           Name: "bastion_host"
           Project: XProfile
           Owner: Bakero
        exact_count: 1
        count_tag:
           Name: "bastion_host"
           Project: XProfile
           Owner: Bakero
        group_id: "{{bastion_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastion-host_out