---
- name: Setup a host for our ansible vpc
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup variable
      include_vars: vars/host_setup

    - name: Import VPC setup variable
      include_vars: vars/output_vars

    - name: Create ec2 key
      ec2_key:
        name: ansible-key
        region: "{{region}}"
      register: key_out

    - name: Save private key into file
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./ansible-key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create a security group
      ec2_group:
          name: ansible-host-sg
          description: security group for the host
          region: "{{region}}"
          vpc_id: "{{vpcid}}"
          rules:
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: "0.0.0.0/0"
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: "0.0.0.0/0"
      register: ansible_sg_out

    - name: creation bastion host
      ec2_instance:
        name: "ansible_host"
        key_name: ansible-key
        region: "{{region}}"
        instance_type: t2.micro
        image_id: "{{bastion_ami}}"
        network:
          assign_public_ip: yes
        wait: yes
        wait_timeout: 300
        tags:
           Name: "bastion_host"
        #count: 1
        security_groups: ["{{ansible_sg_out.group_id}}"]
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastion_host_out
    
    - debug:
        var: bastion_host_out.instances[0].public_ip_address

      