- hosts: localhost
  connection: local
  gather_facts: False
  tasks: 
    - name: Import vpc variables
      include_vars: vars/vpc_setup
    - name: Create xprofile vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout

    #- debug:
        #var: vpcout

    - name: create public subnet 1 in zone 1
      ec2_vpc_subnet:
          vpc_id: "{{vpcout.vpc.id}}"
          state: "{{state}}"
          cidr: "{{PubSub1Cidr}}"
          az: "{{zone1}}"
          region: "{{region}}"
          map_public: yes
          resource_tags:
             Name: xprofile-pubsub1
      register: pubsub1

    - name: create public subnet 2 in zone 2
      ec2_vpc_subnet:
          vpc_id: "{{vpcout.vpc.id}}"
          state: "{{state}}"
          cidr: "{{PubSub2Cidr}}"
          az: "{{zone2}}"
          region: "{{region}}"
          map_public: yes
          resource_tags:
             Name: xprofile-pubsub2
      register: pubsub2

    - name: create public subnet 3 in zone 3
      ec2_vpc_subnet:
          vpc_id: "{{vpcout.vpc.id}}"
          state: "{{state}}"
          cidr: "{{PubSub3Cidr}}"
          az: "{{zone3}}"
          region: "{{region}}"
          map_public: yes
          resource_tags:
             Name: xprofile-pubsub3
      register: pubsub3

    - name: create private subnet 1 in zone 1
      ec2_vpc_subnet:
          vpc_id: "{{vpcout.vpc.id}}"
          state: "{{state}}"
          cidr: "{{PriSub1Cidr}}"
          az: "{{zone1}}"
          region: "{{region}}"
          map_public: yes
          resource_tags:
             Name: xprofile-PriSub1
      register: PriSub1

    - name: create private subnet 2 in zone 2
      ec2_vpc_subnet:
          vpc_id: "{{vpcout.vpc.id}}"
          state: "{{state}}"
          cidr: "{{PriSub2Cidr}}"
          az: "{{zone2}}"
          region: "{{region}}"
          map_public: yes
          resource_tags:
             Name: xprofile-PriSub2
      register: PriSub2

    - name: create private subnet 3 in zone 3
      ec2_vpc_subnet:
          vpc_id: "{{vpcout.vpc.id}}"
          state: "{{state}}"
          cidr: "{{PriSub3Cidr}}"
          az: "{{zone3}}"
          region: "{{region}}"
          map_public: yes
          resource_tags:
             Name: xprofile-PriSub3
      register: PriSub3
    
    - name: create internet gateway
      ec2_vpc_igw:
          vpc_id: "{{vpcout.vpc.id}}"
          state: "{{state}}"
          region: "{{region}}"
          resource_tags:
             Name: xprofile-IGW
      register: igwout

    - name: create new nat gateway and allocate new EIP
      ec2_vpc_nat_gateway:
          subnet_id: "{{pubsub1.subnet.id}}"
          state: "{{state}}"
          region: "{{region}}"
          resource_tags:
             Name: xprofile-NAT
          if_exist_do_not_create: true
      register: natout

    - debug:
        var: natout

    - name: create route table
      ec2_vpc_route_table:
          vpc_id: "{{vpcout.vpc.id}}"
          state: "{{state}}"
          region: "{{region}}"
          resource_tags:
             Name: xprofile-rt
          subnets:
            - "{{ pubsub1.subnet.id }}"
            - "{{ pubsub2.subnet.id }}"
            - "{{ pubsub3.subnet.id }}"
          routes:
            - dest: 0.0.0.0/0
              gateway_id: "{{ natout.nat_gateway_id }}"
      register: rtout

